### ISSUE TITLE
TypeError while installing plugin

### ISSUE THREAD

**Issue by schoeller** [Giswater/giswater_qgis_plugin#500]
Dear all,

thanks for ability to try this open source software at first.

I have downloaded the tag 3.0.117 which coincides with my version of Giswater installed. I then copied the download to a folder in the plugin directory named "giswater". Once trying to install the plugin within Qgis I receive the following error message:

Couldn't load plugin giswater due to an error when calling its initGui() method 

TypeError: coercing to Unicode: need string or buffer, NoneType found 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python\qgis\utils.py", line 342, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/sschoeller/.qgis2/python/plugins\giswater\giswater.py", line 381, in initGui
    self.project_read(False)
  File "C:/Users/sschoeller/.qgis2/python/plugins\giswater\giswater.py", line 545, in project_read
    if not self.manage_layers():
  File "C:/Users/sschoeller/.qgis2/python/plugins\giswater\giswater.py", line 762, in manage_layers
    status = self.populate_audit_check_project(layers)
  File "C:/Users/sschoeller/.qgis2/python/plugins\giswater\giswater.py", line 1000, in populate_audit_check_project
    " VALUES ('" + schema_name + "', '" + table_name + "', '" + db_name + "', '" + host_name + "', 1);")
TypeError: coercing to Unicode: need string or buffer, NoneType found

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.19 Las Palmas, 3a17f72ba5

Any hints appreciated.

Best regards

Sebastian

**Comment by xtorret** [comment]
Dear Sebastian,
You have a compatibility problem. Giswater plugin 3.0.117 is not compatible with schemas created with
