### ISSUE TITLE
Bug on call toolbar

### ISSUE THREAD

**Issue by xtorret** [Giswater/giswater_qgis_plugin#544]
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python\qgis\utils.py", line 342, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/BGeoSoporte/.qgis2/python/plugins\giswater\giswater.py", line 384, in initGui
    self.project_read(False)
  File "C:/Users/BGeoSoporte/.qgis2/python/plugins\giswater\giswater.py", line 559, in project_read
    self.manage_toolbars()
  File "C:/Users/BGeoSoporte/.qgis2/python/plugins\giswater\giswater.py", line 288, in manage_toolbars
    self.manage_toolbar(toolbar_id, list_actions)
UnboundLocalError: local variable 'list_actions' referenced before assignment

**Comment by daviderill** [comment]
Closed by 2794b8a
